### ISSUE TITLE
Back button animation weird transition

### ISSUE THREAD

**Issue by 27px** [codrops/Slicebox#17]
All animation works fine when forward button is pressed but when back button is pressed, it doesn't work. Just click the button you will understand. I couldn't screenshot it. each partition is disappearing and appearing.

**Comment by MarkusVFX** [comment]
Hi Rahul, 
there is fix / pull request  by @tylla   it works for me 
https://github.com/codrops/Slicebox/pull/15/commits/bd9c32b37398bbac2a32986ac73c345f359cce9f

You need to use jquery.slicebox.js, and change lines 702-705  (this.animationStyles)

Best,
M.

**Comment by 27px** [comment]
Yes it works for me too
